# Generated by Django 4.2.1 on 2023-06-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idprod', models.IntegerField(primary_key=True, serialize=False, verbose_name='idProduct')),
                ('nombreproduc', models.CharField(max_length=100, verbose_name='NombreProd')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='imagen')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
