# Generated by Django 4.2.1 on 2023-07-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
